In [51]:
import numpy as np
import os
from PIL import Image

In [169]:
def load_images():    
    rootDir = "photos"
    for dirName, subdirList, fileList in os.walk(rootDir):
        #print("Directory Name:, dirName")
        for filename in fileList:
            print(filename)
#load_images()

In [170]:
def resizing_images():
    main_list = []
    pic = 1
    for i in range(len(fileList)):
        print("Picture Number : ",pic)
        im = Image.open(dirName+"\\"+fileList[i])
        pic_array = np.array(im)
        #print(pic_array)
        re_img = im.resize((200, 200))
        re_array = np.array(re_img)
        print("Size:",re_array.size)
        print("Shape: ",re_array.shape)
        print("======================","\n")
        #print(re_array)
        main_list.append(re_array)
        pic = pic+1
#resizing_images()

In [171]:
def con_into_numpy_array():
    final_array = np.array(main_list)
    print("Final Array of Images: \n\n",final_array)
    len(main_list)
#con_into_numpy_array()

In [172]:
def final_result():
    print(f"Final Shape: {final_array.shape}")
    print(f"Final Size: {final_array.size}")
    print(f"Final Dimension: {final_array.ndim}")

In [181]:
def main():
    #print(load_images())
    #print(resizing_images())
    con_into_numpy_array()
    print("=======================","\n\n")
    final_result()

In [182]:
if __name__ == "__main__":
    main()

Final Array of Images: 

 [[[[ 59  63  66]
   [ 68  72  75]
   [ 56  60  63]
   ...
   [ 11  11  11]
   [ 11  11  11]
   [ 11  11  11]]

  [[ 62  66  69]
   [ 50  54  57]
   [ 54  58  61]
   ...
   [ 11  11  11]
   [ 11  11  11]
   [ 11  11  11]]

  [[ 55  59  62]
   [ 56  60  63]
   [ 76  80  83]
   ...
   [ 11  11  11]
   [ 11  11  11]
   [ 11  11  11]]

  ...

  [[ 37  40  45]
   [ 27  30  35]
   [ 35  38  43]
   ...
   [  7   5   6]
   [  7   5   6]
   [  7   5   6]]

  [[ 32  36  39]
   [ 44  48  51]
   [ 32  36  39]
   ...
   [  7   7   7]
   [  7   7   7]
   [  7   7   7]]

  [[ 39  43  46]
   [ 36  40  43]
   [ 24  28  31]
   ...
   [  7   7   7]
   [  7   7   7]
   [  7   7   7]]]


 [[[197 208 214]
   [197 208 214]
   [198 209 215]
   ...
   [192 205 211]
   [193 204 208]
   [193 204 208]]

  [[197 208 214]
   [197 208 214]
   [198 209 215]
   ...
   [192 205 211]
   [193 204 208]
   [193 204 208]]

  [[197 208 214]
   [197 208 214]
   [198 209 215]
   ...
   [192 205 211]
  