In [1]:
import numpy as np

In [2]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [3]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [5]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
l = [2,3.2,5.5,-6.4,-2.2,2.4]

In [10]:
a = np.array(l)

In [11]:
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

In [12]:
print(a[1])

3.2


In [13]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [14]:
x = [2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]

In [16]:
a = np.array(x)

In [17]:
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [18]:
a[:,3]

array([-6.4,  0.1, 21. ])

In [19]:
a[1:4,0:4]

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

In [20]:
a[1:,2]

array([4. , 2.1])

In [23]:
arr = np.array((np.arange(4),np.arange(10,14)))

In [24]:
print(np.shape(arr))

(2, 4)


In [25]:
arr.size

8

In [27]:
arr.min()

0

In [28]:
arr.max()

13

In [29]:
a = arr.reshape((2,2,2))

In [30]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [31]:
a.T

array([[[ 0, 10],
        [ 2, 12]],

       [[ 1, 11],
        [ 3, 13]]])

In [32]:
a.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [33]:
y = np.array((np.arange(4),np.arange(10,14)),dtype=float)

In [34]:
y

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]])

In [35]:
l = np.arange(0,21)

In [36]:
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [54]:
m_3 = np.arange(3,30,3)

In [55]:
m_3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [56]:
np.random.rand(8)

array([0.4192589 , 0.9043927 , 0.13202249, 0.42396224, 0.24403991,
       0.94496178, 0.25019543, 0.24861506])

In [42]:
a = np.arange(1,9).reshape(2,4)

In [43]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
b = np.array([1,2])

In [50]:
b = b.reshape(2,1)

In [51]:
b

array([[1],
       [2]])

In [52]:
a+b

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])