# *Online portal Work:*

## 2.Numpy Vs Python List: ##

In [1]:
l = range(1000000)

In [2]:
import numpy as np

In [3]:
a = np.arange(1000000)

In [4]:
%time for i in range (1,10):r = [x*2 for x in l]

Wall time: 1.43 s


In [5]:
%time for i in range (1,10):r = a * 2

Wall time: 53 ms


## 3.Multidimensional Array: ##

**Here we'll convert List into array But we can directly create Array by passing a value in it,**

In [6]:
a = [3,4]

In [7]:
b = [2,2]

In [8]:
np.ones(b)

array([[1., 1.],
       [1., 1.]])

In [9]:
np.zeros(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.empty(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange(1,100,11)

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [13]:
np.arange(10,100,12)

array([10, 22, 34, 46, 58, 70, 82, 94])

In [14]:
# For Shape

In [15]:
n = np.arange(1,100,11)
np.shape(n)

(9,)

In [16]:
f = np.zeros((10,10))
np.shape(f)

(10, 10)

In [17]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
q = f.reshape(2,2,5,5)
q

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [19]:
q.dtype

dtype('float64')

In [20]:
q.ndim

4

## 4.Arithmetic with ndarray: ##

In [21]:
a = np.random.randn((10))

In [22]:
b = np.random.randn((10))

In [23]:
a

array([ 0.12884708,  0.0382298 , -0.57482324,  0.40605231, -0.15488252,
       -0.46003404, -1.17652184,  0.24601428, -2.7166701 , -0.65893791])

In [24]:
b

array([-0.76170894, -1.27093844, -1.33379042, -0.09368674,  0.29427465,
       -2.3715927 ,  1.44284421,  1.56475318,  0.01704203, -0.2067641 ])

In [25]:
# Adding 2 arrays

In [26]:
a + b

array([-0.63286186, -1.23270865, -1.90861366,  0.31236557,  0.13939214,
       -2.83162674,  0.26632237,  1.81076746, -2.69962807, -0.865702  ])

In [27]:
a - b

array([ 0.89055603,  1.30916824,  0.75896718,  0.49973906, -0.44915717,
        1.91155866, -2.61936605, -1.3187389 , -2.73371213, -0.45217381])

In [28]:
2 * a

array([ 0.25769417,  0.07645959, -1.14964648,  0.81210463, -0.30976504,
       -0.92006808, -2.35304367,  0.49202856, -5.4333402 , -1.31787581])

In [29]:
1 / a

array([ 7.76113803, 26.15760767, -1.73966522,  2.46273686, -6.45650661,
       -2.17375218, -0.84996297,  4.06480468, -0.36809769, -1.51759368])

In [30]:
a

array([ 0.12884708,  0.0382298 , -0.57482324,  0.40605231, -0.15488252,
       -0.46003404, -1.17652184,  0.24601428, -2.7166701 , -0.65893791])

In [31]:
a > 0

array([ True,  True, False,  True, False, False, False,  True, False,
       False])

In [32]:
a[a > 0]

array([0.12884708, 0.0382298 , 0.40605231, 0.24601428])

## 5.Indexing & Slicing: ##

In [33]:
a = np.array([2,3,5,6,7])

**Normal Indexing**

In [34]:
a[3]

6

**Boolean Indexing**

In [35]:
a > 5

array([False, False, False,  True,  True])

***Now if I want a Value that What's in "True" then,***

In [36]:
a[a > 5]

array([6, 7])

**Fancy Indexing**

In [37]:
a[[0,1]]

array([2, 3])

## Slicing ##

In [38]:
x = np.random.randn(10,10)

In [39]:
x

array([[ 1.69407405, -0.8817163 , -0.50755651,  0.47679389, -0.38872739,
         1.68401975,  1.19452757, -0.57366979,  1.0333036 ,  0.06741427],
       [-0.24002797,  0.86366566, -1.09829001, -0.05453284,  0.82916465,
         0.75716287, -0.56178528, -1.14066941,  0.102018  ,  1.25761524],
       [-0.66538091, -1.08728335, -0.63214707, -0.42095004, -1.37605503,
         1.12377851, -0.08839817, -1.15107517,  2.03866161, -1.09224878],
       [ 1.54158055,  0.13534713,  2.3125222 , -0.14657164,  0.12017413,
         0.12958566, -1.35385661,  1.37373376, -1.57264613,  1.42140315],
       [-0.29712534, -1.40371392,  1.01059401, -0.14166781,  0.49702907,
        -0.79942002, -0.47907672,  0.40939135,  0.70619666,  0.3651407 ],
       [ 1.21143244,  1.55450392,  0.48939358, -0.36283542, -1.5080388 ,
        -0.22352034,  0.96106463, -0.25618109,  0.82913362, -0.97175549],
       [ 0.7091414 ,  0.37113229,  0.06962442, -0.47074975, -2.20410861,
         0.47423052,  1.59242109, -0.53056509

***If I want 1st row then,***

In [40]:
x[0]

array([ 1.69407405, -0.8817163 , -0.50755651,  0.47679389, -0.38872739,
        1.68401975,  1.19452757, -0.57366979,  1.0333036 ,  0.06741427])

***If I want 5th coloumn in 1st row then,***

In [41]:
x[0][4]

-0.3887273926717341

***If I want Odd rows then,***

In [42]:
x[1:10:2]

array([[-0.24002797,  0.86366566, -1.09829001, -0.05453284,  0.82916465,
         0.75716287, -0.56178528, -1.14066941,  0.102018  ,  1.25761524],
       [ 1.54158055,  0.13534713,  2.3125222 , -0.14657164,  0.12017413,
         0.12958566, -1.35385661,  1.37373376, -1.57264613,  1.42140315],
       [ 1.21143244,  1.55450392,  0.48939358, -0.36283542, -1.5080388 ,
        -0.22352034,  0.96106463, -0.25618109,  0.82913362, -0.97175549],
       [-1.33803012, -1.04666411, -0.14887223,  0.50468709, -1.68704568,
         0.31835011,  1.18579789, -1.23992144, -0.10540145,  0.27052301],
       [-0.35233201,  0.39539899,  0.58209607,  0.14776629,  1.96856498,
        -0.84276609, -1.28479277,  0.85508595, -0.76073995,  1.06500899]])

***Now If If I want coloumn from 0 to 4 With all rows in it then,***

In [43]:
x[::,0:4]

array([[ 1.69407405, -0.8817163 , -0.50755651,  0.47679389],
       [-0.24002797,  0.86366566, -1.09829001, -0.05453284],
       [-0.66538091, -1.08728335, -0.63214707, -0.42095004],
       [ 1.54158055,  0.13534713,  2.3125222 , -0.14657164],
       [-0.29712534, -1.40371392,  1.01059401, -0.14166781],
       [ 1.21143244,  1.55450392,  0.48939358, -0.36283542],
       [ 0.7091414 ,  0.37113229,  0.06962442, -0.47074975],
       [-1.33803012, -1.04666411, -0.14887223,  0.50468709],
       [-0.50781593, -0.63852476, -0.79512087, -1.10158614],
       [-0.35233201,  0.39539899,  0.58209607,  0.14776629]])

***Example***

In [44]:
s = np.ones((6,6))

In [45]:
s

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [46]:
s[1:-1,1:-1] = 0

In [47]:
s

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

## 6.Element wise Array:

In [48]:
a = np.array([10,3,6,7,8,12])

In [49]:
np.sqrt(a)

array([3.16227766, 1.73205081, 2.44948974, 2.64575131, 2.82842712,
       3.46410162])

In [50]:
np.power(a,2)

array([100,   9,  36,  49,  64, 144], dtype=int32)

In [51]:
y = np.array([1,2,5,9,13,14])

In [52]:
np.maximum(a,y)

array([10,  3,  6,  9, 13, 14])

## 7.np.where():

In [53]:
salary = np.array([-1,2,40000,50000,100000])

In [54]:
np.where(salary<=5,20000,salary)

array([ 20000,  20000,  40000,  50000, 100000])

In [55]:
np.where(salary<=5,"Invalid input",salary)

array(['Invalid input', 'Invalid input', '40000', '50000', '100000'],
      dtype='<U13')

In [56]:
np.where(salary<=5,"Invalid Input","Valid Salary")

array(['Invalid Input', 'Invalid Input', 'Valid Salary', 'Valid Salary',
       'Valid Salary'], dtype='<U13')

## Methamatical & Statistical Methods:

In [57]:
s = np.array([10,12,8,19,30])

In [58]:
s.mean()

15.8

In [59]:
s.cumsum()

array([10, 22, 30, 49, 79], dtype=int32)

In [60]:
s.cumprod()

array([    10,    120,    960,  18240, 547200], dtype=int32)

In [61]:
a = s > 5

In [62]:
a

array([ True,  True,  True,  True,  True])

In [63]:
a.sum()

5

In [64]:
a.any()

True

In [65]:
a.all()

True

In [66]:
a = s > 10
a

array([False,  True, False,  True,  True])

In [67]:
a.sum()

3

In [68]:
a.any()

True

In [69]:
a.all()

False

In [70]:
s

array([10, 12,  8, 19, 30])

In [71]:
s.sort()

In [72]:
s

array([ 8, 10, 12, 19, 30])

In [73]:
np.unique(s)

array([ 8, 10, 12, 19, 30])

## 9.File Input Output:

In [74]:
a = [1,2,3,4,5]

In [75]:
b = [6,7,8,9]

In [76]:
np.save("testa",a)

In [77]:
t = np.load("testa.npy")

In [78]:
t

array([1, 2, 3, 4, 5])

In [79]:
np.savez("testab",a=a,b=b)

In [80]:
z = np.load("testab.npz")

In [81]:
z

In [82]:
z["a"]

array([1, 2, 3, 4, 5])

## 10.Linear Algebra Function: 

![Screenshot (10)](https://user-images.githubusercontent.com/50514728/66200077-1296eb80-e655-11e9-99d8-5fed3edae230.png)

In [83]:
x = np.random.randn(2,4)

In [84]:
y = np.random.rand(4,2)

In [85]:
x.dot(y)

array([[-1.02563015, -1.05921359],
       [-0.27274742, -0.28289965]])

In [86]:
x.transpose()

array([[-2.58274896, -0.67381031],
       [-0.57397879,  0.22382715],
       [-0.68030396,  0.10300705],
       [ 1.6648324 ,  0.11880238]])

In [87]:
y.trace()

1.3991067698780904

In [88]:
a = np.array([[1,2,3] , [3,4,5]])

In [89]:
b = np.array([4,5,6])

In [90]:
a.dot(b)

array([32, 62])

In [91]:
a.transpose()

array([[1, 3],
       [2, 4],
       [3, 5]])

In [92]:
a.trace

<function ndarray.trace>

## 11.Pseudo random Number:

In [93]:
np.random.seed(3)

In [94]:
np.random.normal(size=(2,3))

array([[ 1.78862847,  0.43650985,  0.09649747],
       [-1.8634927 , -0.2773882 , -0.35475898]])

In [95]:
np.random.uniform(size=(2,2))

array([[0.0514672 , 0.44080984],
       [0.02987621, 0.45683322]])

## Reshaping: 

In [96]:
x = np.random.randn(3,4)

In [97]:
x

array([[-1.31386475,  0.88462238,  0.88131804,  1.70957306],
       [ 0.05003364, -0.40467741, -0.54535995, -1.54647732],
       [ 0.98236743, -1.10106763, -1.18504653, -0.2056499 ]])

In [98]:
x.reshape((2,3,2))

array([[[-1.31386475,  0.88462238],
        [ 0.88131804,  1.70957306],
        [ 0.05003364, -0.40467741]],

       [[-0.54535995, -1.54647732],
        [ 0.98236743, -1.10106763],
        [-1.18504653, -0.2056499 ]]])

In [99]:
x.reshape((2,3,2),order="F")

array([[[-1.31386475,  0.88131804],
        [ 0.98236743, -1.18504653],
        [-0.40467741, -1.54647732]],

       [[ 0.05003364, -0.54535995],
        [ 0.88462238,  1.70957306],
        [-1.10106763, -0.2056499 ]]])

In [100]:
x.reshape((2,3,-1))

array([[[-1.31386475,  0.88462238],
        [ 0.88131804,  1.70957306],
        [ 0.05003364, -0.40467741]],

       [[-0.54535995, -1.54647732],
        [ 0.98236743, -1.10106763],
        [-1.18504653, -0.2056499 ]]])

In [101]:
x

array([[-1.31386475,  0.88462238,  0.88131804,  1.70957306],
       [ 0.05003364, -0.40467741, -0.54535995, -1.54647732],
       [ 0.98236743, -1.10106763, -1.18504653, -0.2056499 ]])

In [102]:
x.ravel()

array([-1.31386475,  0.88462238,  0.88131804,  1.70957306,  0.05003364,
       -0.40467741, -0.54535995, -1.54647732,  0.98236743, -1.10106763,
       -1.18504653, -0.2056499 ])

In [103]:
x.flatten()

array([-1.31386475,  0.88462238,  0.88131804,  1.70957306,  0.05003364,
       -0.40467741, -0.54535995, -1.54647732,  0.98236743, -1.10106763,
       -1.18504653, -0.2056499 ])

## Concatenate:

***Takes a sequence (tuple,list,etc,) of arrays and joins them together in order along the input axis***

In [104]:
a = [[1,2,3],[4,5,6]]

In [105]:
a1 = np.array(a)

In [106]:
b = [[7,8,9],[10,11,12]]

In [107]:
a2 = np.array(b)

In [108]:
np.concatenate((a1,a2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
np.concatenate((a1,a2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

***The same thing that we've done by deciding axis, We can do by just Giving [vstack(where, axis=0), hstack(where, axis=1)]***

In [110]:
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((a1,a2))

## Split:

***-Split slices apart an array into multiple arrays along an x-axis***

In [ ]:
a = np.arange(1,15)

In [ ]:
a

In [ ]:
np.split(a,[3,8,12])

In [ ]:
x = [[1,2,3,4,5],[11,12,13,14,15]]

In [ ]:
v = np.array(x)

In [ ]:
v

In [ ]:
np.split(v,[4,6],axis=1)

In [ ]:
np.split(v,[1],axis=0)

## Tile & Repeat:

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a

In [ ]:
np.repeat(a,2)

In [ ]:
np.tile(a,3)