# *1st Class:*

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 39 ms
Wall time: 1.43 s


In [2]:
nd_array = np.array([1,2,3,4])
print(nd_array)
print(type(nd_array))

list = [2,3,4,5,6]
nd_a = np.array(list)
print(nd_a)
print(type(nd_a))

[1 2 3 4]
<class 'numpy.ndarray'>
[2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
list1 = [1,2,3,4,5]
a = np.zeros(list1)
print(type(list1))
print(a)

<class 'list'>
[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]]


In [4]:
b = np.ones(list1)
print(b)

[[[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]]


In [5]:
c = np.empty(list1)
print(c)

[[[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]]]


In [6]:
d = np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
n_a = np.zeros([0,1,2,3,4])
print(n_a)

[]


In [8]:
n_a = np.zeros([1,2,3,4])
print(n_a)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


# *2nd Class:*

In [9]:
import numpy as np

In [10]:
a = """For many people, the Python programming language has strong appeal. Since its first
appearance in 1991, Python has become one of the most popular interpreted pro‐
gramming languages, along with Perl, Ruby, and others. Python and Ruby have
become especially popular since 2005 or so for building websites using their numer‐
ous web frameworks, like Rails (Ruby) and Django (Python). Such languages are
often called scripting languages, as they can be used to quickly write small programs,
or scripts to automate other tasks. I don’t like the term “scripting language,” as it car‐
ries a connotation that they cannot be used for building serious software. Among
interpreted languages, for various historical and cultural reasons, Python has devel‐
oped a large and active scientific computing and data analysis community. In the last
10 years, Python has gone from a bleeding-edge or “at your own risk” scientific com‐
puting language to one of the most important languages for data science, machine
learning, and general software development in academia and industry"""

In [11]:
x = np.array(a.split())

In [12]:
x

array(['For', 'many', 'people,', 'the', 'Python', 'programming',
       'language', 'has', 'strong', 'appeal.', 'Since', 'its', 'first',
       'appearance', 'in', '1991,', 'Python', 'has', 'become', 'one',
       'of', 'the', 'most', 'popular', 'interpreted', 'pro‐', 'gramming',
       'languages,', 'along', 'with', 'Perl,', 'Ruby,', 'and', 'others.',
       'Python', 'and', 'Ruby', 'have', 'become', 'especially', 'popular',
       'since', '2005', 'or', 'so', 'for', 'building', 'websites',
       'using', 'their', 'numer‐', 'ous', 'web', 'frameworks,', 'like',
       'Rails', '(Ruby)', 'and', 'Django', '(Python).', 'Such',
       'languages', 'are', 'often', 'called', 'scripting', 'languages,',
       'as', 'they', 'can', 'be', 'used', 'to', 'quickly', 'write',
       'small', 'programs,', 'or', 'scripts', 'to', 'automate', 'other',
       'tasks.', 'I', 'don’t', 'like', 'the', 'term', '“scripting',
       'language,”', 'as', 'it', 'car‐', 'ries', 'a', 'connotation',
       'that', '

In [13]:
print(len(x))

168


In [14]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [15]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [16]:
d3 = np.array([[1,2,3,4], [5,6,7,8]])
print(d3)
print(len(d3))
print(d3.size)
print(d3.shape)
print(d3.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2
8
(2, 4)
2


In [17]:
arr = np.array([[1,2,3],[4,5,6]])

In [18]:
arr2 = np.array([2])

In [19]:
arr3 = arr * arr2

In [20]:
arr3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [21]:
arr4 = np.array([12,-45,67,89,34,-2,-2,6,-7,8])

In [22]:
arr4

array([ 12, -45,  67,  89,  34,  -2,  -2,   6,  -7,   8])

In [23]:
print(arr4[[4,3,0,6]])

[34 89 12 -2]


In [24]:
print(np.cumsum(arr4))

[ 12 -33  34 123 157 155 153 159 152 160]


In [25]:
x = arr4 > 10

In [26]:
x

array([ True, False,  True,  True,  True, False, False, False, False,
       False])

In [27]:
d3 = np.array([ [
                  [111, 112, 113] , 
                  [121, 122, 123] 
                ],
                [ 
                  [211, 212, 213] , 
                  [221, 222, 224] 
                ],
                [
                  [311, 312, 313], 
                  [321, 322, 323]
                ],
                [
                  [411, 412, 413],
                  [421, 422, 423] 
                ]
              ])
print("array", d3)
print("size", d3.size)
print("shape", d3.shape)
print("dimensions", d3.ndim)
print(x)
print(type(x))            

array [[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 224]]

 [[311 312 313]
  [321 322 323]]

 [[411 412 413]
  [421 422 423]]]
size 24
shape (4, 2, 3)
dimensions 3
[ True False  True  True  True False False False False False]
<class 'numpy.ndarray'>


In [28]:
text = "Here are some of the things you’ll find in NumPy:"
l = text.split(" ")
arr = np.array(text.split(" "))
prn = print
prn("testing")
print(arr)
lnth = np.vectorize(len)
print(arr[lnth(arr)<5])
#print(arr[( np.vectorize(len)) (arr) <5]) 
print()
# text1 = "How dare you! You can't do that! Mr. Ashhad focus on the class"
# text1 += "Do you want break? or if you don't want: we can practice."
# print(text1) 


testing
['Here' 'are' 'some' 'of' 'the' 'things' 'you’ll' 'find' 'in' 'NumPy:']
['Here' 'are' 'some' 'of' 'the' 'find' 'in']



In [29]:
t= "Here are some of the things you’ll find in NumPy"
l = t.split(" ")
arr = np.array(t.split(" "))
prn = print
prn("Testing")
print(arr)
#for a in arr:
#    if len(a) < 5:
#        print(a)

lnth = np.vectorize(len)
print(arr[lnth(arr)<5])
#print(arr[(np.vectorize(len))(arr)<5]) 

#text1 = "How dare you! You can't do that! Mr. Ashhad focus on the class"
#text1 += "Do you want break? or if you don't want: we can practice."
#print(text1) 

Testing
['Here' 'are' 'some' 'of' 'the' 'things' 'you’ll' 'find' 'in' 'NumPy']
['Here' 'are' 'some' 'of' 'the' 'find' 'in']


# *3rd Class:*

In [30]:
a = np.arange(20)

In [31]:
a = np.zeros([5,4,3,2])

In [32]:
a

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [

In [33]:
a.shape

(5, 4, 3, 2)

In [34]:
a.ndim

4

In [35]:
a[:1,:1] = 5

In [36]:
a

array([[[[5., 5.],
         [5., 5.],
         [5., 5.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [

In [37]:
a = np.zeros([2,3,2,3])
a[0,0,0,1] = 5
a

array([[[[0., 5., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [38]:
x = np.zeros([2,3,2,3])
x[1,1,0,1:3] = 7
x

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 7., 7.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

### absolute function [np.abs]

In [39]:
np.fabs?

In [40]:
arr = np.zeros(4)

In [41]:
arr = arr + (-1)
arr

array([-1., -1., -1., -1.])

In [42]:
np.abs(arr)

array([1., 1., 1., 1.])

### np.where

In [43]:
x = np.arange(20)
np.where(x<10,x,x*10)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [44]:
x<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

### mean, cumsum, cumprod, sum(), any(), all():

In [45]:
a = np.arange(10)

In [46]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b = np.arange(20)

In [48]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
b.mean()

9.5

In [50]:
a.mean()

4.5

In [51]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [52]:
x = np.array([1,2,3,4,5])

In [53]:
x.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

### np.unique & np.sort:

In [54]:
y = np.array([1,1,33,33,45,67,67])

In [55]:
np.unique(y)

array([ 1, 33, 45, 67])

In [56]:
np.sort(y)

array([ 1,  1, 33, 33, 45, 67, 67])

### save, load & savez:

In [57]:
a = [1,2,3,4]

In [58]:
np.save("list.npy",a)

In [59]:
np.load("list.npy")

array([1, 2, 3, 4])

In [60]:
a = [1,2,3]
b = [3,4,5]

In [61]:
np.savez("abd",a=a, b=b)

In [62]:
s = np.load("abd.npz")

In [63]:
s

In [64]:
s["a"]

array([1, 2, 3])

In [65]:
s["b"]

array([3, 4, 5])

### Seed:

In [66]:
np.random.seed(7)
perm = np.random.rand(3)
print(perm)

[0.07630829 0.77991879 0.43840923]


In [67]:
np.random.seed(7)
print(np.random.rand(3))

[0.07630829 0.77991879 0.43840923]


### Order "C" and "F":

In [68]:
arr = np.arange(1,13)
arr.reshape((3,4),order = "F")

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [69]:
arr = np.arange(1,13)
arr.reshape((3,4),order = "C")

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### split:

In [70]:
arr = np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [71]:
np.split(arr,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80, 90])]

In [72]:
arr = np.arange(10,110,10)

In [73]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [74]:
np.split(arr,[2,4,6,8])

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]