In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
iris = pd.read_csv("iris.csv")
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
iris = iris.sample(frac = 1)
iris.tail()

sepal.length  sepal.width  petal.length  petal.width     variety
100           6.3          3.3           6.0          2.5   Virginica
110           6.5          3.2           5.1          2.0   Virginica
13            4.3          3.0           1.1          0.1      Setosa
38            4.4          3.0           1.3          0.2      Setosa
93            5.0          2.3           3.3          1.0  Versicolor

In [4]:
iris.shape

(150, 5)

In [5]:
iris_new = np.array(iris.drop(["variety"], axis = 1))
iris_new

array([[6.6, 2.9, 4.6, 1.3],
       [7.7, 2.8, 6.7, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [5.9, 3.2, 4.8, 1.8],
       [5.5, 4.2, 1.4, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.8, 2.6, 4. , 1.2],
       [6.7, 3.1, 4.7, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.3, 4.4, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [6.9, 3.1, 5.1, 2.3],
       [7. , 3.2, 4.7, 1.4],
       [7.3, 2.9, 6.3, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3.1, 5.6, 2.4],
       [6.4, 3.2, 4.5, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [4.9, 3.6, 1.4, 0.1],
       [6.7, 3.3, 5.7, 2.1],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [6.5, 3. , 5.8, 2.2],
       [5.7, 2.6, 3.5, 1. ],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.2, 2. ],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [6.1, 3. , 4.6, 1.4],
       [5.7, 2

In [6]:
iris_new.shape

(150, 4)

In [7]:
variety = np.array(iris["variety"])
variety

array(['Versicolor', 'Virginica', 'Versicolor', 'Versicolor', 'Setosa',
       'Setosa', 'Versicolor', 'Versicolor', 'Virginica', 'Versicolor',
       'Setosa', 'Virginica', 'Versicolor', 'Virginica', 'Versicolor',
       'Virginica', 'Virginica', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Virginica',
       'Setosa', 'Setosa', 'Virginica', 'Versicolor', 'Versicolor',
       'Versicolor', 'Virginica', 'Virginica', 'Virginica', 'Setosa',
       'Versicolor', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Versicolor',
       'Versicolor', 'Versicolor', 'Setosa', 'Setosa', 'Versicolor',
       'Versicolor', 'Setosa', 'Setosa', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Versicolor', 'Setosa', 'Setosa', 'Virginica',
       'Setosa', 'Virginica', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Setosa', 

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
variety = le.fit_transform(variety)
variety

array([1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 0, 2, 1, 2, 1, 2, 2, 1, 2, 0, 2, 0,
       0, 2, 1, 0, 0, 1, 1, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 2, 1, 2, 1, 0, 0, 2,
       0, 2, 1, 2, 0, 2, 0, 2, 2, 1, 0, 2, 1, 1, 1, 0, 0, 1, 2, 2, 1, 1,
       0, 2, 2, 0, 2, 2, 0, 1, 2, 0, 0, 1, 2, 1, 1, 0, 0, 2, 0, 2, 0, 2,
       2, 1, 2, 2, 2, 1, 2, 1, 0, 0, 2, 0, 2, 0, 1, 1, 0, 1, 1, 1, 2, 1,
       1, 0, 1, 1, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 0, 1])

In [9]:
from tensorflow.keras.utils import to_categorical
enc_variety = tf.keras.utils.to_categorical(variety)
enc_variety

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_new, enc_variety, test_size = 0.2, random_state = 42)

In [11]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(120, 4)
(120, 3)
(30, 4)
(30, 3)


In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(12, input_shape = (4,)))
model.add(Dense(8, activation = "relu"))
model.add(Dense(3, activation = "softmax"))

In [13]:
model.compile(optimizer = "adam",
             loss = "categorical_crossentropy",
             metrics = ["acc"])

In [14]:
model.fit(x_train, y_train, epochs = 50, validation_split = 0.1, batch_size = 12, verbose = 2)

Train on 108 samples, validate on 12 samples
Epoch 1/50
108/108 - 1s - loss: 4.2989 - acc: 0.3333 - val_loss: 4.2834 - val_acc: 0.4167
Epoch 2/50
108/108 - 0s - loss: 3.3638 - acc: 0.3333 - val_loss: 3.3700 - val_acc: 0.4167
Epoch 3/50
108/108 - 0s - loss: 2.6358 - acc: 0.3333 - val_loss: 2.6070 - val_acc: 0.4167
Epoch 4/50
108/108 - 0s - loss: 2.0399 - acc: 0.2963 - val_loss: 1.9350 - val_acc: 0.3333
Epoch 5/50
108/108 - 0s - loss: 1.5280 - acc: 0.2500 - val_loss: 1.3561 - val_acc: 0.4167
Epoch 6/50
108/108 - 0s - loss: 1.1654 - acc: 0.2870 - val_loss: 1.0536 - val_acc: 0.4167
Epoch 7/50
108/108 - 0s - loss: 1.0714 - acc: 0.3148 - val_loss: 0.9994 - val_acc: 0.4167
Epoch 8/50
108/108 - 0s - loss: 1.0463 - acc: 0.3426 - val_loss: 0.9709 - val_acc: 0.4167
Epoch 9/50
108/108 - 0s - loss: 1.0119 - acc: 0.3426 - val_loss: 0.9490 - val_acc: 0.4167
Epoch 10/50
108/108 - 0s - loss: 0.9757 - acc: 0.3704 - val_loss: 0.9381 - val_acc: 0.4167
Epoch 11/50
108/108 - 0s - loss: 0.9523 - acc: 0.5093 

In [15]:
evaluation = model.evaluate(x_test, y_test, verbose = 2)
print("Loss: ",evaluation[0])
print("Accuracy: ",evaluation[1])

30/30 - 0s - loss: 0.3937 - acc: 0.9333
Loss:  0.39374634623527527
Accuracy:  0.93333334


In [29]:
i = 8
prediction =  model.predict_classes(x_test[i].reshape(1,4))

In [30]:
if prediction == 0:
  print("Data for prediction :",x_test[i], "\n", "Prediction: ",prediction)
  print("Actual label :",y_test[i])

elif prediction == 1:
  print("Data for prediction :",x_test[i], "\n", "Prediction: ",prediction)
  print("Actual label :",y_test[i])

else:
  print("Data for prediction :",x_test[i], "\n", "Prediction: ",prediction)
  print("Actual label :",y_test[i])

Data for prediction : [5.7 2.9 4.2 1.3] 
 Prediction:  [1]
Actual label : [0. 1. 0.]
