In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.optimizers import Adam

In [4]:
sonar = pd.read_csv("datasets/sonar.csv")
sonar.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

In [5]:
sonar = sonar.sample(frac = 1)
sonar.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
80   0.0100  0.0194  0.0155  0.0489  0.0839  0.1009  0.1627  0.2071  0.2696   
5    0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
167  0.0015  0.0186  0.0289  0.0195  0.0515  0.0817  0.1005  0.0124  0.1168   
58   0.0125  0.0152  0.0218  0.0175  0.0362  0.0696  0.0873  0.0616  0.1252   
106  0.0428  0.0555  0.0708  0.0618  0.1215  0.1524  0.1543  0.0391  0.0610   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
80   0.2990  ...  0.0130  0.0073  0.0077  0.0075  0.0060  0.0080  0.0019   
5    0.3513  ...  0.0201  0.0248  0.0131  0.0070  0.0138  0.0092  0.0143   
167  0.1476  ...  0.0108  0.0075  0.0089  0.0036  0.0029  0.0013  0.0010   
58   0.1302  ...  0.0041  0.0074  0.0030  0.0050  0.0048  0.0017  0.0041   
106  0.0113  ...  0.0142  0.0179  0.0079  0.0060  0.0131  0.0089  0.0084   

     0.0090  0.0032  R  
80   0.0053  0.0019  R  
5    0.0036  0.0103  R  
167  0.0032  0.0047  M  
58   0.0086  0.0058  R  
106  0.0113  0.0049  M  

[5 rows x 61 columns]

In [6]:
sonar_new = sonar.drop(["R"], axis = 1).values
scale = StandardScaler()
sonar_new_scale = scale.fit_transform(sonar_new)
sonar_new_scale

array([[-0.83579208, -0.57776433, -0.73740932, ..., -0.9346337 ,
        -0.4265097 , -0.91989765],
       [ 0.10842322,  1.73414308,  2.29683303, ...,  0.98197394,
        -0.70154866,  0.75149005],
       [-1.20564599, -0.60203632, -0.38870565, ..., -1.07374232,
        -0.76626371, -0.36276841],
       ...,
       [-0.42242593, -0.52011834, -0.98982913, ...,  0.2400613 ,
        -0.9442301 , -0.24338358],
       [ 1.46600465,  2.064849  ,  2.83029759, ..., -0.3472862 ,
         0.54421605,  1.30861929],
       [-0.68785051, -0.64451231, -0.6775572 , ..., -0.85735113,
        -0.84715752, -0.48215325]])

In [7]:
sonar_new.shape

(207, 60)

In [8]:
target = sonar["R"]
print(target)

80     R
5      R
167    M
58     R
106    M
      ..
59     R
56     R
31     R
99     M
169    M
Name: R, Length: 207, dtype: object


In [9]:
le = LabelEncoder()
target_enc = le.fit_transform(target)
print(target_enc)

[1 1 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 1 1 0 1 0 0 0 0
 0 0 1 0 1 1 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 1 1 1 1 0 0
 0 0 1 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0
 1 1 0 0 0 1 0 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 1 1 1 0
 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 0]


In [10]:
target_ohe = tf.keras.utils.to_categorical(target_enc)
print(target_ohe)

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 

In [11]:
x_train, x_test, y_train, y_test = train_test_split(sonar_new_scale, target_ohe, test_size = 0.2)

In [12]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(165, 60)
(165, 2)
(42, 60)
(42, 2)


In [13]:
model = Sequential()
model.add(Dropout(0.2, input_shape = (60,)))
model.add(Dense(60, activation = "relu"))
model.add(Dense(30, activation = "relu"))
model.add(BatchNormalization())
model.add(Dense(2, activation = "softmax"))

In [14]:
optimize = Adam(learning_rate = 0.005)

model.compile(optimizer = optimize,
             loss = "categorical_crossentropy",
             metrics = ["acc"])

In [15]:
history = model.fit(x_train, y_train, batch_size = 6, epochs = 40, validation_split = 0.1)

Train on 148 samples, validate on 17 samples
Epoch 1/40
148/148 [==============================] - 1s 4ms/sample - loss: 0.6806 - acc: 0.6757 - val_loss: 0.5926 - val_acc: 0.5882
Epoch 2/40
148/148 [==============================] - 0s 423us/sample - loss: 0.4230 - acc: 0.8176 - val_loss: 0.5857 - val_acc: 0.5882
Epoch 3/40
148/148 [==============================] - 0s 391us/sample - loss: 0.4377 - acc: 0.8378 - val_loss: 0.6255 - val_acc: 0.6471
Epoch 4/40
148/148 [==============================] - 0s 398us/sample - loss: 0.4219 - acc: 0.7838 - val_loss: 0.4391 - val_acc: 0.7647
Epoch 5/40
148/148 [==============================] - 0s 371us/sample - loss: 0.3494 - acc: 0.8784 - val_loss: 0.4109 - val_acc: 0.7059
Epoch 6/40
148/148 [==============================] - 0s 398us/sample - loss: 0.3062 - acc: 0.8446 - val_loss: 0.4276 - val_acc: 0.7647
Epoch 7/40
148/148 [==============================] - 0s 411us/sample - loss: 0.2933 - acc: 0.9054 - val_loss: 0.3786 - val_acc: 0.7059
Epoch

In [16]:
evaluation = model.evaluate(x_test, y_test, verbose = 2)
print(model.metrics_names)
print(evaluation)

42/42 - 0s - loss: 0.2418 - acc: 0.9286
['loss', 'acc']
[0.24175661784552394, 0.9285714]


In [17]:
prediction = model.predict_classes(x_test)[0]
prediction

0

In [18]:
y_test[0]

array([1., 0.], dtype=float32)