**Importing tensorflow**

In [1]:
import tensorflow as tf

**Importing MNIST Dataset**

In [2]:
mnist = tf.keras.datasets.mnist

**Splitting the MNIST dataset into Training and Testing**

In [3]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()

**As this Dataset is alreeady in vectorized form So checking the first image's array**

In [4]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

**Checking Label**

In [5]:
y_train[0]

5

**Checking the shape of dataset that we splitted into Training and Testing**

In [6]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


**Checking the Dimensions of dataset that we splitted into Training and Testing**

In [7]:
print(x_train.ndim)
print(x_test.ndim)
print(y_train.ndim)
print(y_test.ndim)

3
3
1
1


**Checking the visual form**

In [8]:
import matplotlib.pyplot as plt
digit = x_train[10]
plt.imshow(digit, cmap = plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

**Checking the label of Image we just visualized**

In [9]:
y_train[10]

3

**1- Changing Dimension of train sets into 2**

**2- As you can see above there are multiple values between 0 to 255 and 255 is Max value so what we're doing is managing the values between 0 and 1 by dividing the train sets by 255.**

In [10]:
x_train = x_train.reshape(60000, 28 * 28)
x_test = x_test.reshape(10000, 28 * 28)

x_train, x_test = x_train/255.0, x_test/255.0

**Checking Dimension**

In [11]:
print(x_train.ndim)
print(x_test.ndim)

2
2


In [12]:
x_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

**One hot encoding**

In [13]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train) 
y_test = to_categorical(y_test)

In [14]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

**Building Neural Network**

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(512, activation = "relu", input_shape = (28 * 28,)))
model.add(Dense(10, activation = "softmax"))

**Model Compilation**

In [16]:
model.compile(optimizer = "adam",
             loss = "categorical_crossentropy",
             metrics = ["accuracy"])

**Checking our Training Accuracy of Model by passing training sets**

In [24]:
model.fit(x_train, y_train, epochs = 6, batch_size = 128,verbose=0)

**Checking our Testing Accuracy of Model by passing training sets**

In [25]:
loss, acc = model.evaluate(x_test, y_test,verbose=0)

In [26]:
print("Loss: ", loss)
print("Accuracy: ", acc)

Loss:  0.06374386335728487
Accuracy:  0.9816


**Prediction**

In [29]:
model.predict_classes(x_test)[100]

6

In [36]:
import numpy as np
print(np.arange(10))
print(y_test[100])

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
